# **Recitation 8**

In this lab, the Revised Simplex Method to solve the following linear program (in standard inequality form).

$$
\begin{aligned}
\operatorname{maximize} & c^{T} x \\
\text { subject to } & A x \leq b \\
& x \geq 0
\end{aligned}
$$

where

$$
A=\left[\begin{array}{rrrrr}
3 & 1 & 3 & 2 & 1 \\
1 & -1 & 4 & 1 & 0 \\
2 & 2 & -1 & 4 & 2 \\
3 & 6 & 1 & 3 & 3
\end{array}\right] \quad, \quad c=\left[\begin{array}{l}
2 \\
3 \\
0 \\
4 \\
1
\end{array}\right], \quad b=\left[\begin{array}{r}
18 \\
3 \\
28 \\
39
\end{array}\right]
$$

Use `numpy` to do the calculations. A quick review of `numpy` is below.

Introduce slack variables first, and use them as the initial basic variables. Use the smallest subscript rule to choose entering and leaving variables. At each step, clearly show the basis, the current values of the basic variables, the vector $y$, the top-row coefficients $\bar{c}_{j}$ you compute, the entering variable, the vector $d$, the number $t$, and the leaving variable.

#**Reference: Useful Numpy Commands**

Import numpy package:

In [1]:
import numpy as np

Define a vector:

In [ ]:
f = np.array([[1, 0, 2, -1]]) # Notice the double brackets
print(f)

[[ 1  0  2 -1]]


Transposition:

In [ ]:
c = f.T
print(c)

[[ 1]
 [ 0]
 [ 2]
 [-1]]


Entering a matrix:

In [ ]:
A = np.array([[1, -1, 3, 5],
              [1, 1, 2, 4]])
print(A)

[[ 1 -1  3  5]
 [ 1  1  2  4]]


Extracting multiple columns:

In [ ]:
# Extracts 2nd and 3rd column
# Python is 0-indexed i.e. counting starts at 0
# Ranges exclude the last number, so "a:b" actually spans a, a+1, ..., b-1
print(A[:,1:3])

[[-1  3]
 [ 1  2]]


Extracting a single column:

In [ ]:
# Use backets on the single-column index to keep it vertical
print(A[:,[1]])

[[-1]
 [ 1]]


A list of subscripts:

In [ ]:
B = [1, 3]
print(B)

[1, 3]


Extracting the matrix with those corresponding columns:

In [ ]:
E = A[:,B]
print(E)

[[-1  5]
 [ 1  4]]


Solving the equation $E x = b$:

In [ ]:
b = np.array([[2],[7]])
print(b)

[[2]
 [7]]


In [ ]:
x = np.linalg.solve(E, b)
print(x)

[[3.]
 [1.]]


Scalar multiplication:

In [ ]:
d = np.array([[6], [3]])
print(d)
print(2*d)

[[6]
 [3]]
[[12]
 [ 6]]


Vector addition:

In [ ]:
print(b + d)

[[ 8]
 [10]]


Elementwise division of vectors:

In [ ]:
print (b / d)

[[0.33333333]
 [2.33333333]]


Matrix multiplication:

In [ ]:
print(E @ b)

[[33]
 [30]]


Creating identity matrices

In [ ]:
I = np.eye(2)
print(I)

[[1. 0.]
 [0. 1.]]


Verticle matrix stacking:



In [ ]:
print(np.vstack([E, I]))

[[-1.  5.]
 [ 1.  4.]
 [ 1.  0.]
 [ 0.  1.]]


Horizontal matrix stacking:

In [ ]:
print(np.hstack([E, I]))

[[-1.  5.  1.  0.]
 [ 1.  4.  0.  1.]]


**# Revised Simplex Method**

In [2]:
# Define the matrix A with 4 extra columns being the 4x4 identity

# ADD YOUR CODE BELOW:
A = np.array([[3, 1, 3, 2, 1],
              [1, -1, 4, 1, 0],
              [2, 2, -1, 4, 2],
              [3, 6, 1, 3, 3]])
A = np.hstack([A, np.eye(4)])

print(A)

[[ 3.  1.  3.  2.  1.  1.  0.  0.  0.]
 [ 1. -1.  4.  1.  0.  0.  1.  0.  0.]
 [ 2.  2. -1.  4.  2.  0.  0.  1.  0.]
 [ 3.  6.  1.  3.  3.  0.  0.  0.  1.]]


In [3]:
# Define column vector b
# ADD YOUR CODE BELOW:
b = np.array([[18, 3, 28, 39]]).T

# Define vector column vector c with 4 augmented zeroes
# ADD YOUR CODE BELOW:
c = np.array([[2, 3, 0, 4, 1, 0, 0, 0, 0]]).T

print(b)
print(c)

[[18]
 [ 3]
 [28]
 [39]]
[[2]
 [3]
 [0]
 [4]
 [1]
 [0]
 [0]
 [0]
 [0]]


In [4]:
# Indices of basic variables, B
# ADD YOUR CODE BELOW:
B = np.array(range(5,9))
print(B)

[5 6 7 8]


In [5]:
# Extract basic columns
# ADD YOUR CODE BELOW:
A_B = A[:,B]
print(A_B)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [ ]:
# Find starting basic solution
# ADD YOUR CODE BELOW:
x_B = ???
print(x_B)

In [ ]:
# Calculate y vector
# ADD YOUR CODE BELOW:
y = ???
print(y)

In [ ]:
# Calculate reduced costs
# ADD YOUR CODE BELOW:
c_hat = ???
print(c_hat)

In [ ]:
# Choose entering variable index and apply ratio test
# ADD YOUR CODE BELOW:
entering = ???
ratio    = ???
print(ratio)

In [ ]:
# Choose the smallest positive ratio
# ADD YOUR CODE BELOW:
t = ???
print(t)

In [ ]:
# Identify the leaving index
leaving = ???
print(leaving)

In [ ]:
# Define new basic indices
# ADD YOUR CODE BELOW:
B[???] = ???
print(B)

Repeat above until all reduced-costs are negative.
Create one or more code blocks per iteration.



In [ ]:
# ADD YOUR CODE BELOW:

# (Make more code blocks if needed)

In [ ]:
# Once all reduce costs are negative, calculate objective
OBJ_VAL = ???
print(OBJ_VAL)